## 01. Import Libraries

In [11]:
# import libraries

import pandas as pd
import numpy as np
import os
import requests
import json
from datetime import datetime

## 02. Import Data

In [34]:
# importing Bike Sharing Data from Each QMonth (2022)

# Create a list with all files in the folder using a list comprehension
# pulling the data from the Data file of our project folder

# WHY are we using a list comprehension:
# in this case we have 12 files, and loading/merging each file individually can be tedious and cumbersome
# in order to streamline, we are using a list comprehension.


# first, we are creating a folderpath variable and indicating that it is from our data folder (hence the r"Data")
# then we get into the list comprehension.. start by creating filepath (this will be our list and return the name of all files in the list)
# breaking down each part individually we have our loop:
    # for name in os.listdir(folderpath) if name.endswith(.csv') : this will loop through the folder and add it to the list if it meets the name reqs
    # os.path.join(folderpath, name) will join the folderpath with the file name, creating the path for our data :)


# after my initial attempt, a few other files populated, so decided to add the "if ends with .csv" to filter those out.

folderpath = r"Data"
filepath = [os.path.join(folderpath, name) for name in os.listdir(folderpath) if name.endswith('.csv')]

filepath

['Data/202208-citibike-tripdata_3.csv',
 'Data/202207-citibike-tripdata_2.csv',
 'Data/202207-citibike-tripdata_3.csv',
 'Data/202208-citibike-tripdata_2.csv',
 'Data/202207-citibike-tripdata_1.csv',
 'Data/202208-citibike-tripdata_1.csv',
 'Data/202210-citibike-tripdata_1.csv',
 'Data/202207-citibike-tripdata_4.csv',
 'Data/202208-citibike-tripdata_4.csv',
 'Data/202203-citibike-tripdata_2.csv',
 'Data/202210-citibike-tripdata_2.csv',
 'Data/202203-citibike-tripdata_1.csv',
 'Data/202210-citibike-tripdata_3.csv',
 'Data/202204-citibike-tripdata_1.csv',
 'Data/202204-citibike-tripdata_2.csv',
 'Data/202204-citibike-tripdata_3.csv',
 'Data/202211-citibike-tripdata_3.csv',
 'Data/202202-citibike-tripdata_1.csv',
 'Data/202211-citibike-tripdata_2.csv',
 'Data/202202-citibike-tripdata_2.csv',
 'Data/202209-citibike-tripdata_4.csv',
 'Data/202206-citibike-tripdata_4.csv',
 'Data/202211-citibike-tripdata_1.csv',
 'Data/202209-citibike-tripdata_1.csv',
 'Data/202206-citibike-tripdata_1.csv',
 'Data/202206-citibike-tripdata_3.csv',
 'Data/202209-citibike-tripdata_2.csv',
 'Data/202209-citibike-tripdata_3.csv',
 'Data/202206-citibike-tripdata_2.csv',
 'Data/202205-citibike-tripdata_3.csv',
 'Data/202205-citibike-tripdata_2.csv',
 'Data/202205-citibike-tripdata_1.csv',
 'Data/202201-citibike-tripdata_2.csv',
 'Data/202212-citibike-tripdata_1.csv',
 'Data/202201-citibike-tripdata_1.csv',
 'Data/202212-citibike-tripdata_2.csv']

In [38]:
# now that all data sets are in the list, time to read & concatenate the data sets:

df = pd.concat((pd.read_csv(f, low_memory=False) for f in filepath), ignore_index=True)

df.head(5)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,9D0DC440CB40CF8E,electric_bike,2022-08-27 13:56:47.728,2022-08-27 14:02:56.651,Flatbush Ave & Ocean Ave,3704.04,3 St & Prospect Park West,3865.05,40.663657,-73.963014,40.668132,-73.973638,casual
1,2214991DFBE5C4D7,electric_bike,2022-08-20 10:37:02.756,2022-08-20 10:45:56.631,Forsyth St\t& Grand St,5382.07,E 11 St & 1 Ave,5746.14,40.717798,-73.993161,40.729538,-73.984267,casual
2,20C5D469563B6337,classic_bike,2022-08-31 18:55:03.051,2022-08-31 19:03:37.344,Perry St & Bleecker St,5922.07,Grand St & Greene St,5500.02,40.735354,-74.004831,40.721700,-74.002381,member
3,3E8791885BC189D1,classic_bike,2022-08-02 08:05:00.250,2022-08-02 08:16:52.063,FDR Drive & E 35 St,6230.04,Grand Army Plaza & Central Park S,6839.10,40.744219,-73.971212,40.764397,-73.973715,member
4,8DBCBF98885106CB,electric_bike,2022-08-25 15:44:48.386,2022-08-25 15:55:39.691,E 40 St & 5 Ave,6474.11,Ave A & E 14 St,5779.11,40.752052,-73.982115,40.730311,-73.980472,member

In [40]:
df.tail(5)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
29838801,1F223EDAFF420AE3,electric_bike,2022-12-01 20:26:45.847,2022-12-01 20:30:46.012,Avenue D & E 3 St,5436.09,Stanton St & Chrystie St,5523.02,40.720701,-73.977939,40.722293,-73.991475,member
29838802,CFA5C560ACB73B8E,classic_bike,2022-12-26 13:46:34.237,2022-12-26 13:52:43.900,43 Ave & 47 St,6209.05,39 Ave & 45 St,6401.03,40.744806,-73.917290,40.749478,-73.918265,member
29838803,11C8C5E0DB947B07,classic_bike,2022-12-01 05:56:14.903,2022-12-01 06:06:10.357,Avenue D & E 3 St,5436.09,Bleecker St & Crosby St,5679.08,40.720828,-73.977932,40.726156,-73.995102,member
29838804,5B9B083C534A5964,classic_bike,2022-12-02 11:54:15.871,2022-12-02 12:01:00.747,Montague St & Clinton St,4677.06,Sands St & Jay St,4821.03,40.694271,-73.992327,40.700119,-73.986200,member
29838805,91C286C462F89A50,classic_bike,2022-12-18 13:35:22.574,2022-12-18 13:37:27.193,Montague St & Clinton St,4677.06,Cadman Plaza E & Tillary St,4677.01,40.694271,-73.992327,40.695977,-73.990149,member

In [42]:
df.shape

(29838806, 13)

In [44]:
# going to export this to .csv so we have it handy for future use:

df.to_csv('combined_bike_rides_2022.csv')

In [48]:
# performing some consistency checks:
# null values
# duplicate ride ids
# inconsistencies with station names
# taking a random sample of the dataframe so it is more workable

In [51]:
# check for missing or null values:

df.isnull().sum()

ride_id                   0
rideable_type             0
started_at                0
ended_at                  0
start_station_name       49
start_station_id         49
end_station_name      70092
end_station_id        70092
start_lat                 0
start_lng                 0
end_lat               37392
end_lng               37392
member_casual             0
dtype: int64

In [56]:
# going to remove all null values (our dataframe is large enough that this won't affect our analysis)

df = df.dropna()
df.shape

(29768714, 13)

In [59]:
# going to check for duplicates now. 
# its expected to have duplicate station names, latitudes, temps, etc
# so I'm just going to check the ride_id for duplicates

(df['ride_id'].duplicated()).value_counts()

ride_id
False    29768714
Name: count, dtype: int64

In [62]:
# no duplicate ride ids,
# going to check for consistency across our non numerical variables:

# check for consistency in rideable_type

df['rideable_type'].value_counts()

rideable_type
classic_bike     18074213
electric_bike    11694501
Name: count, dtype: int64

In [69]:
# check for consistency in member

df['member_casual'].value_counts()

member_casual
member    23214744
casual     6553970
Name: count, dtype: int64

In [71]:
# check for consistency in station ids

df['start_station_id'].value_counts()

start_station_id
6140.05    126075
5329.03    120801
6948.10    111076
6364.07    103697
6822.09    103153
            ...
3853.02         3
4920.11         3
4113.01         3
8141.01         1
3934.06         1
Name: count, Length: 3468, dtype: int64

In [73]:
# check for consistency in station ids

df['start_station_id'].value_counts()

start_station_id
6140.05    126075
5329.03    120801
6948.10    111076
6364.07    103697
6822.09    103153
            ...
3853.02         3
4920.11         3
4113.01         3
8141.01         1
3934.06         1
Name: count, Length: 3468, dtype: int64

In [76]:
# it looks like all stations are formatted similarly! now we can take a random sample of our dataframe before integrating our weather data!

In [80]:
# when sampling, I want my results to be reproducible, so I will be using a random state
# then exporting this dataframe once I have integrated the weather data.

In [82]:
# going to use half of our dataframe:

df1 = df.sample(frac=0.50, random_state=42)
df1.size

193496641

In [84]:
df1.shape

(14884357, 13)

In [88]:
# this is still really large and things are moving slowly, going to take another random sample.

# going to use half of our dataframe:

df2 = df1.sample(frac=0.50, random_state=43)
df2.shape

(7442178, 13)

In [90]:
# going to export this to .csv so we have it handy for future use:

df2.to_csv('combined_bike_rides_2022_sampled.csv')

## 03. Import Weather Data

In [95]:
# import the weather data 
# noaa la guardia airport id: GHCND:USW00014732

In [97]:
# Define NOAA token:

Token = 'zfMjWUYOnNKcTKqvOfbLLpElqHIpOiRo'

In [99]:
# request for data with parameters:

r = requests.get('https://www.ncdc.noaa.gov/cdo-web/api/v2/data?datasetid=GHCND&datatypeid=TAVG&limit=1000&stationid=GHCND:USW00014732&startdate=2022-01-01&enddate=2022-12-31', headers={'token':Token})

In [101]:
# load API response as JSON file:

d = json.loads(r.text)  

# double check to make sure this worked :)

d

{'metadata': {'resultset': {'offset': 1, 'count': 365, 'limit': 1000}},
 'results': [{'date': '2022-01-01T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 116},
  {'date': '2022-01-02T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 114},
  {'date': '2022-01-03T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 14},
  {'date': '2022-01-04T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': -27},
  {'date': '2022-01-05T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 32},
  {'date': '2022-01-06T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 49},
  {'date': '2022-01-07T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 7},
  {'date': '2022-01-08T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': -25},
  {'date': '2022-01-09T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 14},
  {'date': '2022-01-10T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 16},
  {'date': '2022-01-11T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': -54},
  {'date': '2022-01-12T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': -19},
  {'date': '2022-01-13T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 40},
  {'date': '2022-01-14T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 48},
  {'date': '2022-01-15T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': -67},
  {'date': '2022-01-16T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': -80},
  {'date': '2022-01-17T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 39},
  {'date': '2022-01-18T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 18},
  {'date': '2022-01-19T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 32},
  {'date': '2022-01-20T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 51},
  {'date': '2022-01-21T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': -60},
  {'date': '2022-01-22T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': -59},
  {'date': '2022-01-23T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': -7},
  {'date': '2022-01-24T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': -2},
  {'date': '2022-01-25T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 36},
  {'date': '2022-01-26T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': -23},
  {'date': '2022-01-27T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': -42},
  {'date': '2022-01-28T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 1},
  {'date': '2022-01-29T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': -48},
  {'date': '2022-01-30T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': -71},
  {'date': '2022-01-31T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': -34},
  {'date': '2022-02-01T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': -17},
  {'date': '2022-02-02T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 23},
  {'date': '2022-02-03T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 64},
  {'date': '2022-02-04T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 58},
  {'date': '2022-02-05T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': -28},
  {'date': '2022-02-06T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': -48},
  {'date': '2022-02-07T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 5},
  {'date': '2022-02-08T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 41},
  {'date': '2022-02-09T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 28},
  {'date': '2022-02-10T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 63},
  {'date': '2022-02-11T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 86},
  {'date': '2022-02-12T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 118},
  {'date': '2022-02-13T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 28},
  {'date': '2022-02-14T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': -43},
  {'date': '2022-02-15T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': -47},
  {'date': '2022-02-16T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 16},
  {'date': '2022-02-17T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 116},
  {'date': '2022-02-18T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 99},
  {'date': '2022-02-19T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 1},
  {'date': '2022-02-20T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': -26},
  {'date': '2022-02-21T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 41},
  {'date': '2022-02-22T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 56},
  {'date': '2022-02-23T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 144},
  {'date': '2022-02-24T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 11},
  {'date': '2022-02-25T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 8},
  {'date': '2022-02-26T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': -11},
  {'date': '2022-02-27T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 24},
  {'date': '2022-02-28T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 8},
  {'date': '2022-03-01T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 26},
  {'date': '2022-03-02T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 77},
  {'date': '2022-03-03T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 56},
  {'date': '2022-03-04T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': -19},
  {'date': '2022-03-05T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 31},
  {'date': '2022-03-06T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 96},
  {'date': '2022-03-07T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 182},
  {'date': '2022-03-08T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 87},
  {'date': '2022-03-09T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 32},
  {'date': '2022-03-10T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 40},
  {'date': '2022-03-11T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 72},
  {'date': '2022-03-12T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 51},
  {'date': '2022-03-13T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': -23},
  {'date': '2022-03-14T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 53},
  {'date': '2022-03-15T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 116},
  {'date': '2022-03-16T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 136},
  {'date': '2022-03-17T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 82},
  {'date': '2022-03-18T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 139},
  {'date': '2022-03-19T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 131},
  {'date': '2022-03-20T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 143},
  {'date': '2022-03-21T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 104},
  {'date': '2022-03-22T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 107},
  {'date': '2022-03-23T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 72},
  {'date': '2022-03-24T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 57},
  {'date': '2022-03-25T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 96},
  {'date': '2022-03-26T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 104},
  {'date': '2022-03-27T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 59},
  {'date': '2022-03-28T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': -15},
  {'date': '2022-03-29T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': -12},
  {'date': '2022-03-30T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 26},
  {'date': '2022-03-31T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 99},
  {'date': '2022-04-01T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 131},
  {'date': '2022-04-02T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 72},
  {'date': '2022-04-03T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 70},
  {'date': '2022-04-04T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 76},
  {'date': '2022-04-05T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 97},
  {'date': '2022-04-06T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 86},
  {'date': '2022-04-07T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 91},
  {'date': '2022-04-08T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 128},
  {'date': '2022-04-09T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 114},
  {'date': '2022-04-10T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 86},
  {'date': '2022-04-11T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 88},
  {'date': '2022-04-12T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 134},
  {'date': '2022-04-13T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 154},
  {'date': '2022-04-14T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 163},
  {'date': '2022-04-15T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 157},
  {'date': '2022-04-16T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 157},
  {'date': '2022-04-17T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 83},
  {'date': '2022-04-18T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 79},
  {'date': '2022-04-19T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 76},
  {'date': '2022-04-20T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 94},
  {'date': '2022-04-21T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 106},
  {'date': '2022-04-22T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 146},
  {'date': '2022-04-23T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 133},
  {'date': '2022-04-24T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 128},
  {'date': '2022-04-25T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 104},
  {'date': '2022-04-26T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 115},
  {'date': '2022-04-27T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 116},
  {'date': '2022-04-28T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 82},
  {'date': '2022-04-29T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 104},
  {'date': '2022-04-30T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 129},
  {'date': '2022-05-01T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 136},
  {'date': '2022-05-02T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 121},
  {'date': '2022-05-03T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 124},
  {'date': '2022-05-04T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 120},
  {'date': '2022-05-05T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 172},
  {'date': '2022-05-06T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 148},
  {'date': '2022-05-07T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 100},
  {'date': '2022-05-08T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 104},
  {'date': '2022-05-09T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 135},
  {'date': '2022-05-10T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 154},
  {'date': '2022-05-11T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 161},
  {'date': '2022-05-12T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 171},
  {'date': '2022-05-13T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 160},
  {'date': '2022-05-14T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 179},
  {'date': '2022-05-15T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 188},
  {'date': '2022-05-16T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 204},
  {'date': '2022-05-17T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 197},
  {'date': '2022-05-18T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 178},
  {'date': '2022-05-19T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 155},
  {'date': '2022-05-20T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 154},
  {'date': '2022-05-21T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 212},
  {'date': '2022-05-22T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 278},
  {'date': '2022-05-23T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 210},
  {'date': '2022-05-24T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 174},
  {'date': '2022-05-25T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 162},
  {'date': '2022-05-26T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',
   'value': 164},
  {'date': '2022-05-27T00:00:00',
   'datatype': 'TAVG',
   'station': 'GHCND:USW00014732',
   'attributes': 'H,,S,',

## 04. Wrangle JSON data:

In [104]:
# for the purpose of this project, we are only interested in the average daily temp and the date
# when looking at d (our JSON data) we can see that we have our results, 'date' and 'TAVG'

In [106]:
# for avg temps, use a list comprehension again:

avg_temp = [item for item in d['results'] if item['datatype']=='TAVG']

# this willstore/access the average temp in our d (JSON results) as long as the datatype within d is == TAVG (our average temp)

In [108]:
# now we want to get the date for each of these averages:

date_of_temp = [item['date'] for item in avg_temp]

# date_of_temp

In [110]:
# now to get the temperature from our avg_temp

temp = [item['value'] for item in avg_temp]

# now that we have a list of dates, and a list of temps, we can combine this with our data set (bike rides)

In [112]:
# before we can merge this to our data set, we will need to make a new dataframe and populate it with this temp and date_of_temp

df_temp = pd.DataFrame()

df_temp['date'] = [datetime.strptime(d, "%Y-%m-%dT%H:%M:%S") for d in date_of_temp]

# this will strip the date column of any attribute aside from date (hour, minute, second, etc)
# now to make sure its in the format we want!

df_temp['date'] = pd.to_datetime(df_temp['date'], format='%Y-%m-%d').dt.date

df_temp

           date
0    2022-01-01
1    2022-01-02
2    2022-01-03
3    2022-01-04
4    2022-01-05
..          ...
360  2022-12-27
361  2022-12-28
362  2022-12-29
363  2022-12-30
364  2022-12-31

[365 rows x 1 columns]

In [114]:
# now lets add in our average temp in a new column!

df_temp['average_temp'] = [float(x)/10.0 for x in temp]

# this is going to make sure the temperature from the temp list created above is a float and rounded to the the nearest tenth of a degree

In [116]:
df_temp

           date  average_temp
0    2022-01-01          11.6
1    2022-01-02          11.4
2    2022-01-03           1.4
3    2022-01-04          -2.7
4    2022-01-05           3.2
..          ...           ...
360  2022-12-27          -0.7
361  2022-12-28           3.4
362  2022-12-29           6.4
363  2022-12-30           9.3
364  2022-12-31           8.2

[365 rows x 2 columns]

In [118]:
# we have two columns and 365 days, meaning we did this correctly!
# going to export this to a .csv (just in case), then begin merging with our other dataframe

df_temp.to_csv(r"Data/average_daily_temps_2022.csv")

## 05. Merge Both Data Sets

In [121]:
# it's now time to merge the df_temp with our bike rides dataset (df)
# we will be using the date as the common key (column) with which to complete the merge!

In [125]:
# first we need to ensure that the date in the rides df is stripped of any time and ONLY represents the date
# following the same process as above

df2['started_at'] = pd.to_datetime(df2['started_at'], format='%Y-%m-%d %H:%M:%S.%f')

# this is taking the 'started_at' column from our dataframe and converting it to date_time format

df2['date'] = pd.to_datetime(df2['started_at']).dt.date

# this step is creating a new 'date' column within our dataframe and populating it with JUST the date from our 'started_at' column

df2.head(5)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,date
18311778,F2E235CF6C94C4AE,classic_bike,2022-11-05 17:56:05.905,2022-11-05 18:09:57.700,5 Ave & E 29 St,6248.06,W 35 St & 9 Ave,6569.09,40.745168,-73.986831,40.754145,-73.996089,member,2022-11-05
11610400,52D4E9186C185927,classic_bike,2022-10-25 18:21:18.372,2022-10-25 18:38:15.674,45 St & 4 Ave,3275.03,17 St & 5 Ave,3699.07,40.649145,-74.009486,40.663493,-73.991007,member,2022-10-25
9221628,0A3A3A00DEB36556,electric_bike,2022-10-10 18:12:58.401,2022-10-10 18:19:03.820,South St & Pike St,5159.07,Cliff St & Fulton St,5065.14,40.709947,-73.991542,40.708380,-74.004950,member,2022-10-10
4767694,59D536E3C44FF806,classic_bike,2022-07-19 08:30:56.306,2022-07-19 08:52:40.254,E 1 St & 1 Ave,5593.01,1 Ave & E 62 St,6753.08,40.723356,-73.988650,40.761227,-73.960940,member,2022-07-19
8888624,C441A6C657E7E420,electric_bike,2022-10-19 21:38:45.089,2022-10-19 21:56:47.120,W 35 St & 9 Ave,6569.09,Washington St & Barrow St,5847.08,40.754145,-73.996089,40.731911,-74.008769,casual,2022-10-19

In [127]:
# now that we have a correctly formatted 'date' column in each dataframe, we can complete the merge!

# creating a new dataframe for the merged data!

df_merged = pd.DataFrame()

# we are using a left merge here! 
# Why? Bc our 'df' dataframe has more rows and we want to ensure that each entry is assigned a temp that corresponds with the date!
# this means that there will be bike rides with the same avg temp ( as more than one ride was taken daily)

df_merged = df2.merge(df_temp, how = 'left', on = 'date', indicator = True) 

# we are merging on the column 'date' as mentioned above!
# check to see if it worked!

df_merged

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,date,average_temp,_merge
0,F2E235CF6C94C4AE,classic_bike,2022-11-05 17:56:05.905,2022-11-05 18:09:57.700,5 Ave & E 29 St,6248.06,W 35 St & 9 Ave,6569.09,40.745168,-73.986831,40.754145,-73.996089,member,2022-11-05,19.4,both
1,52D4E9186C185927,classic_bike,2022-10-25 18:21:18.372,2022-10-25 18:38:15.674,45 St & 4 Ave,3275.03,17 St & 5 Ave,3699.07,40.649145,-74.009486,40.663493,-73.991007,member,2022-10-25,16.9,both
2,0A3A3A00DEB36556,electric_bike,2022-10-10 18:12:58.401,2022-10-10 18:19:03.820,South St & Pike St,5159.07,Cliff St & Fulton St,5065.14,40.709947,-73.991542,40.708380,-74.004950,member,2022-10-10,15.8,both
3,59D536E3C44FF806,classic_bike,2022-07-19 08:30:56.306,2022-07-19 08:52:40.254,E 1 St & 1 Ave,5593.01,1 Ave & E 62 St,6753.08,40.723356,-73.988650,40.761227,-73.960940,member,2022-07-19,28.2,both
4,C441A6C657E7E420,electric_bike,2022-10-19 21:38:45.089,2022-10-19 21:56:47.120,W 35 St & 9 Ave,6569.09,Washington St & Barrow St,5847.08,40.754145,-73.996089,40.731911,-74.008769,casual,2022-10-19,10.0,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7442173,B3BB654752F0F5B1,classic_bike,2022-11-09 12:59:20.087,2022-11-09 13:03:32.565,Bergen St & Smith St,4446.01,Congress St & Hicks St,4497.09,40.686744,-73.990632,40.689395,-73.999513,member,2022-11-09,8.7,both
7442174,E57B721D204C28CE,electric_bike,2022-12-21 15:26:01.770,2022-12-21 15:35:31.348,9 Ave & W 18 St,6190.08,E 22 St & 2 Ave,5971.09,40.743174,-74.003664,40.737169,-73.981225,member,2022-12-21,1.0,both
7442175,0073B660660B92ED,classic_bike,2022-08-02 17:52:37.424,2022-08-02 18:27:53.830,Motorgate,6814.01,Southpoint Park,6566.01,40.763909,-73.947721,40.753702,-73.958652,casual,2022-08-02,26.4,both
7442176,E2FCB2B1D246D5E8,classic_bike,2022-06-02 08:25:30.025,2022-06-02 08:45:30.889,Hancock St & Bedford Ave,4255.05,S 4 St & Wythe Ave,5204.05,40.682166,-73.953990,40.712859,-73.965903,casual,2022-06-02,20.3,both
7442177,3876C474975BAF92,classic_bike,2022-08-14 13:50:43.901,2022-08-14 13:52:34.013,Allen St & Hester St,5342.10,Allen St & Hester St,5342.10,40.716059,-73.991908,40.716059,-73.991908,casual,2022-08-14,24.0,both

In [129]:
# this appears to have worked! 
# we know from above that our df has 895485 rows, so lets check to make sure each row was assigned an average_temp

df_merged['_merge'].value_counts(dropna = False)

_merge
both          7442058
left_only         120
right_only          0
Name: count, dtype: int64

In [133]:
# we are going to drop the 120 entries that only merged on the left, then remove the merge column, then export our merged dataframe!

df3 = df_merged[df_merged['_merge'] != 'left_only']
df3['_merge'].value_counts(dropna = False)

_merge
both          7442058
left_only           0
right_only          0
Name: count, dtype: int64

In [136]:
df3 = df3.drop('_merge', axis=1)
df3.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,date,average_temp
0,F2E235CF6C94C4AE,classic_bike,2022-11-05 17:56:05.905,2022-11-05 18:09:57.700,5 Ave & E 29 St,6248.06,W 35 St & 9 Ave,6569.09,40.745168,-73.986831,40.754145,-73.996089,member,2022-11-05,19.4
1,52D4E9186C185927,classic_bike,2022-10-25 18:21:18.372,2022-10-25 18:38:15.674,45 St & 4 Ave,3275.03,17 St & 5 Ave,3699.07,40.649145,-74.009486,40.663493,-73.991007,member,2022-10-25,16.9
2,0A3A3A00DEB36556,electric_bike,2022-10-10 18:12:58.401,2022-10-10 18:19:03.820,South St & Pike St,5159.07,Cliff St & Fulton St,5065.14,40.709947,-73.991542,40.708380,-74.004950,member,2022-10-10,15.8
3,59D536E3C44FF806,classic_bike,2022-07-19 08:30:56.306,2022-07-19 08:52:40.254,E 1 St & 1 Ave,5593.01,1 Ave & E 62 St,6753.08,40.723356,-73.988650,40.761227,-73.960940,member,2022-07-19,28.2
4,C441A6C657E7E420,electric_bike,2022-10-19 21:38:45.089,2022-10-19 21:56:47.120,W 35 St & 9 Ave,6569.09,Washington St & Barrow St,5847.08,40.754145,-73.996089,40.731911,-74.008769,casual,2022-10-19,10.0

In [138]:
# we've dropped any incomplete merges, and the _merge column, now we can export this for future use!

df3.to_csv(r"Data/merged_temp_ride_data.csv")